# fly.toml app configuration file generated for paypack-logs on 2023-04-26T18:16:10+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "paypack-logs"
primary_region = "lhr"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  ORG = "paypack"
  SUBJECT = "logs.>"
  UPTRACE_PROJECT_DSN = "https://Xyj8XDYxsfUIl-HFNMJv3A@uptrace.dev/115"

[metrics]
  port = 9598
  path = "/metrics"
