[sinks.uptrace]
  type = "http"
  inputs = ["log_json"]
  encoding.codec = "ndjson"
  compression = "gzip"
  uri = "https://api.uptrace.dev/api/v1/vector-logs"
  headers.uptrace-dsn = "${UPTRACE_PROJECT_DSN}"

